### ISSUE TITLE
An executable file in the repository

### ISSUE THREAD

**Issue by AdrianJaneczko** [microsoft/ajaxmin#1]
We are using a command line AjaxMin.exe tool (version 4.45.4416.14250) in our solution. It's used as one of the MSBuild tasks defined in our project file. Currently we are migrating our project from .NET Framework 3.5 version to .NET Framework 4.6.

The problem we have is that AjaxMin.exe command doesn't work on the environment without 3.5 .NET Framework installed.

We tried to generate an executable file from AjaxMin solution from repo. We generated our own .snk file and built. But the output .exe file is still not working without .NET Framework 3.5. Our output .exe file has 5.15.6851.30012 version. The error we got:

`The command "AjaxMinifier.exe -JS -comments:none -rename:none -clobber -xml AjaxMin-full-paths.xml" exited with code 1.	`

I wonder if it's possible that you push .exe file to the repo? Or maybe an installer file? I can see that it was hosted on CodePlex site before.

Then we could check if it's a problem with the way we are building .exe file or maybe this tool in fact requires .NET Framework 3.5 to be installed.

Thank you,
Adrian

**Comment by seankeating** [comment]
@AdrianJaneczko - I have added the latest release (v5.14) of AjaxMin to GitHub.  You can find it here:  [https://github.com/Microsoft/ajaxmin/releases/tag/v5.14](https://github.com/Microsoft/ajaxmin/releases/tag/v5.14)  I'll close this for now, let me know if it doesn't help resolve your issues.
