### ISSUE TITLE
Computed property name brakes minifier...

### ISSUE THREAD

**Issue by kepeter** [microsoft/ajaxmin#10]
Hi,
When I'm using computed property names to create object, the minified version is totally broken...

**Original:**
`var i = 0;
var a = {
    ['foo' + ++i]: i,
    ['foo' + ++i]: i,
    ['foo' + ++i]: i
};`

**Minified**
`var i=0,a={}["foo"+ ++i];i;["foo"+ ++i];i;["foo"+ ++i];i`

I'm using version 5.14.5506.26202 (latest for now)...

**Comment by seankeating** [comment]
This project is no longer being maintained.
