### ISSUE TITLE
Please, support fields in javascript classes, at least  public and static public fields

### ISSUE THREAD

**Issue by tbebekis** [microsoft/ajaxmin#12]
Please, support fields in javascript classes, at least  public and static public fields

```
class A {

   constructor() {
   }

   Field;
   Field2 = 123;
   static Field3;
   static Field4 = 123; 
}
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_fields

**Comment by seankeating** [comment]
This project is no longer being maintained.
