### ISSUE TITLE
Does Ajaxmin support removal of dead code?

### ISSUE THREAD

**Issue by petrosmm** [microsoft/ajaxmin#3]
In various projects I have worked on, developers leave a lot of dead code in the comments mostly for debugging purposes, however that code get's transported and it does not get removed... Before writing here, I came across this issue with @Taritsyn of the WebMarkUpMin project as well as [NUglify](https://github.com/xoofx/NUglify/issues/67) JS minifer project. Does ajaxmin support removing dead code -- the 'if (false' statements)?

**Comment by seankeating** [comment]
It doesn't appear it has the support for removing dead code from if statements like:
`if (false) { ... }`
   
But it does support removing unused functions.

Here is the test I ran with the latest release (v5.14):
**Test JavaScript:**
```js
function foo() {
    if (false) {
      console.log("I'll never be true.");
    }
    console.log("I'll always be used.");
    function unused() {
      console.log("I'm unused.");
    }
}
```
**AjaxMinifer Command:**
```command
AjaxMinifier.exe deadCodeTest.js -out deadCodeTest.min.js
```

**Output:**
```js
function foo(){!1&&console.log("I'll never be true.");console.log("I'll always be used.")}
```

**Comment by seankeating** [comment]
I think what you are looking for is called "Tree Shaking":  [https://webpack.js.org/guides/tree-shaking/](https://webpack.js.org/guides/tree-shaking/)

I have not tested to verify.

**Comment by seankeating** [comment]
I tested with roolup.js which supports Tree Shaking.

**Test Code:**
```js
(function foo() {
    if (false) {
      console.log("I'll never be true.");
    }

    console.log("I'll always be used.");

    function unused() {
      console.log("I'm unused.");
    }
})();
```

**rollup command**
```command
rollup deadCodeTest.js --file deadCodeTest.min2.js --format iife
```

**Output:**
```js
(function () {
    'use strict';

    (function foo() {
        console.log("I'll always be used.");
    })();
}());
```

**Comment by petrosmm** [comment]
Hmm interesting... I have never heard that term before and I will look into it. Thank you!
