### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by ca0v** [microsoft/ajaxmin#4]
The docs are from 2009 and I'm interested in generating map files.  Can you add something to the readme?

**Comment by seankeating** [comment]
I'm currently working on getting latest documents into the Wiki.
I have got the source map section up here: https://github.com/Microsoft/ajaxmin/wiki/Source-Maps 

Note: I am getting all the documentation up, but it is taking some time.  Let me know if there is something missing that you need.

**Comment by seankeating** [comment]
This project is no longer being maintained.
