### ISSUE TITLE
2 variables in scope given same name

### ISSUE THREAD

**Issue by gwynge** [microsoft/ajaxmin#6]
I installed from nuget in Visual studio [version: 5.14.5506.26196, runtime version: v4.0.30319]

and used 
Dim jsMinifier As New Minifier
Dim minifiedCode As String = jsMinifier.MinifyJavaScript(unminifiedCode)

and it minified the following snippet:
   
 addColumns(cols) {
        for (let col of cols) {
            let colControl = new ColumnReordererRow(this, col);
            this.columnArea.add(colControl.getComponent());
        }
    }

as

addColumns(n){for(let n of n){let t=new ColumnReordererRow(this,n);this.columnArea.add(t.getComponent())}}

both col and cols have been renamed as "n" which of course doesn't work!

**Comment by seankeating** [comment]
This project is no longer being maintained.
